export default class Constants {
  static readonly KEYS: string[] = ['C', '/', 'x', 'Back', '7', '8', '9', '-', '4', '5', '6', '+', '1', '2', '3', '=', '0', '.']
  static readonly OP_KEYS: string[] = ['Back', 'C', '/', 'x', '+', '-', '=']
  static readonly CALC_KEYS: string[] = ['/', 'x', '+', '-']
  static readonly VAL_KEYS: string[] = ['7', '8', '9', '4', '5', '6', '1', '2', '3','0']
  static readonly DOT_KEY: string = '.'
  static readonly DISPLAY_TEXT_SIZE: number = 36
}